### ISSUE TITLE
RSS not syncing

### ISSUE THREAD

**Issue by north93** [kindlyfire/mdrss-ts#1]
It's been about a week since I've received any update from the RSS feeds I had generated, but when I enter in mangadex there are new chapters. Also, if I try to generate a new RSS feed, it shows empty, not showing even the past chapters.

**Comment by kindlyfire** [comment]
Could you send me the RSS feeds that are empty? As far as I can see on the feed for [all English chapters](https://mdrss.tijlvdb.me/feed?q=tl:en), it is still fetching chapters as expected

**Comment by north93** [comment]
I have this [RSS feed](https://mdrss.tijlvdb.me/feed?q=manga:192aa767-2479-42c1-9780-8d65a2efd36a,group:e906bd0b-f98b-40c1-8ca2-02b5c51b5092) or [this one](https://mdrss.tijlvdb.me/feed?q=manga:4141c5dc-c525-4df5-afd7-cc7d192a832f,group:e906bd0b-f98b-40c1-8ca2-02b5c51b5092) that don't update with new chapters.
I also made [this other one](https://mdrss.tijlvdb.me/feed?q=manga:63e54dfd-f7a9-473e-a591-28558e229c5b,group:434457d1-59ba-412a-b5d4-586d2377d11f) that shows as empty.

**Comment by kindlyfire** [comment]
The first one doesn't return the latest chapter as the group you are filtering for did not publish a scanlation for it yet
Second one seems to have missed a chapter, which is possible for a few reasons, maybe the same one as below

Third one is empty because the chapters by the group you are filtering for didn't originally get posted by that group. The group that originally posted them was deleted and the chapters edited to show a new group. Due to how MDRSS is built, it is not able to pick up on updates to the data of chapters. Whatever the groups and uploader were at the time of creation will be saved by MDRSS indefinitely. This is by design
